apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret
spec:
  authentication:
    kubernetesAuth:
      secretsScope:
        projectSlug: test-b
        envSlug: prod

  managedKubeSecretReferences:
    - secretNamespace: test-b-prod